### ISSUE TITLE
'Library' object has no attribute 'panel_options'

### ISSUE THREAD

**Issue by alexandrabrown** [jasonrbr/CodeReader#77]
@thebenismightier do you know how to resolve this? Were you working on that part?

**Comment by alexandrabrown** [comment]
Happens when I try to reed a library

**Comment by thebenismightier** [comment]
is this resolved, or nonissue?

**Comment by thebenismightier** [comment]
@leftoverBits

**Comment by leftoverBits** [comment]
This is an issue that can easily be fixed. We should not be able to "read" a library because they have no body. Just have the children menu list the available library declarations verbatim. If the user selects a library, that same children menu is just regenerated. Assign me to this task if you'd like me to take it over.

**Comment by thebenismightier** [comment]
i was just seeing if you took it over or not since you closed it

**Comment by alexandrabrown** [comment]
I'm still getting this issue when I read a library so I'm reopening this.

**Comment by alexandrabrown** [comment]
Ok idk what happened but I guess it's not an issue anymore
